/* automatically generated by rust-bindgen 0.60.1 */

extern "C" {
    pub fn ema_mp4_mux_create_clang(
        handle: *mut *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn ema_mp4_mux_destroy_clang(handle: *mut ::std::os::raw::c_void);
}
extern "C" {
    pub fn ema_mp4_mux_set_video_framerate_clang(
        handle: *mut ::std::os::raw::c_void,
        nome: ::std::os::raw::c_uint,
        deno: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn ema_mp4_mux_set_input_clang(
        handle: *mut ::std::os::raw::c_void,
        fn_: *const ::std::os::raw::c_char,
        lang: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        enc_name: *const ::std::os::raw::c_char,
        time_scale: ::std::os::raw::c_uint,
        chunk_span_size: ::std::os::raw::c_uint,
        tid: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn ema_mp4_mux_set_output_clang(
        handle: *mut ::std::os::raw::c_void,
        buf_out: ::std::os::raw::c_int,
        fn_: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn ema_mp4_mux_set_moov_timescale_clang(
        handle: *mut ::std::os::raw::c_void,
        timescale: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn ema_mp4_mux_set_mbrand_clang(
        handle: *mut ::std::os::raw::c_void,
        mbrand: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn ema_mp4_mux_set_cbrand_clang(
        handle: *mut ::std::os::raw::c_void,
        cbrand: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn ema_mp4_mux_set_output_format_clang(
        handle: *mut ::std::os::raw::c_void,
        outfm: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn ema_mp4_mux_set_max_duration_clang(
        handle: *mut ::std::os::raw::c_void,
        max_duration: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn ema_mp4_mux_set_dv_profile_clang(
        handle: *mut ::std::os::raw::c_void,
        profile: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn ema_mp4_mux_set_dv_bl_compatible_id_clang(
        handle: *mut ::std::os::raw::c_void,
        compatible_id: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn ema_mp4_mux_set_sampleentry_dvh1_clang(
        handle: *mut ::std::os::raw::c_void,
        es_idx: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn ema_mp4_mux_set_sampleentry_hvc1_clang(
        handle: *mut ::std::os::raw::c_void,
        es_idx: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn ema_mp4_mux_consistency_check_clang(handle: *mut ::std::os::raw::c_void);
}
extern "C" {
    pub fn ema_mp4_mux_start_clang(handle: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_uint;
}
